# Generated by Django 2.0.2 on 2018-02-25 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blindspotapp', '0002_auto_20180221_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='vseries',
        ),
    ]
