# Generated by Django 2.0.2 on 2018-02-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blindspotapp', '0004_auto_20180225_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='perc_vis',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
