# Generated by Django 2.0.2 on 2018-03-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blindspotapp', '0005_vehicles_perc_vis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicles',
            options={'ordering': ['vmake']},
        ),
    ]
